### ISSUE TITLE
Agregar mas a la descripcion

### ISSUE THREAD

**Issue by ferjoaguilar** [VicFlores/Ponencia#2]
Hola buenas tarde siento que la descripcion esta demasiado corta puedes poner:

1. Lugar de procedencia
2. Tus cargos anteriores
3. El nombre de tu mascota

:V

**Comment by VicFlores** [comment]
Yo veo unos cuantos más: primero, los ataques a la apariencia física (foca, ballena, orangután, zampabollos, piltrafilla, feo, cara- seguido de lo que sea, carapán, carapiña, caracandado, y de ahí pasamos a los famosos boca-, como bocachancla, bocabuzón y similares). Segundo, no los más
